apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: sentinel-routing
  namespace: monitoring
  labels:
    alertmanagerConfig: sentinel
spec:
  route:
    receiver: "null"
    groupBy: [alertname, cluster, severity]
    groupWait: 30s
    groupInterval: 5m
    repeatInterval: 4h
    routes:
      - matchers:
          - name: severity
            value: critical
        receiver: sns-critical
        repeatInterval: 1h
      - matchers:
          - name: severity
            value: warning
        receiver: sns-warning
        repeatInterval: 6h
  receivers:
    - name: "null"
    - name: sns-critical
      webhookConfigs:
        - url: "http://sns-forwarder.monitoring.svc.cluster.local:8080/critical"
          sendResolved: true
    - name: sns-warning
      webhookConfigs:
        - url: "http://sns-forwarder.monitoring.svc.cluster.local:8080/warning"
          sendResolved: true
  inhibitRules:
    - sourceMatch:
        - name: severity
          value: critical
      targetMatch:
        - name: severity
          value: warning
      equal: [alertname, cluster, node]
