apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod-azure
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: platform@sentinel.example.com
    privateKeySecretRef:
      name: letsencrypt-prod-azure
    solvers:
      - dns01:
          azureDNS:
            subscriptionID: "<AZURE_SUBSCRIPTION_ID>"
            resourceGroupName: "<DNS_RESOURCE_GROUP>"
            hostedZoneName: sentinel.example.com
            environment: AzurePublicCloud
            managedIdentity:
              clientID: "<CERT_MANAGER_IDENTITY_CLIENT_ID>"
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging-azure
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: platform@sentinel.example.com
    privateKeySecretRef:
      name: letsencrypt-staging-azure
    solvers:
      - dns01:
          azureDNS:
            subscriptionID: "<AZURE_SUBSCRIPTION_ID>"
            resourceGroupName: "<DNS_RESOURCE_GROUP>"
            hostedZoneName: sentinel.example.com
            environment: AzurePublicCloud
            managedIdentity:
              clientID: "<CERT_MANAGER_IDENTITY_CLIENT_ID>"
