name: Pre-commit Hooks

on:
  pull_request:
    branches: [main]

jobs:
  pre-commit:
    name: Lint and Format Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.9.x"

      - uses: pre-commit/action@v3.0.1
